[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
intuition = "https://rpc.intuition.systems/http"
intuition_testnet = "https://rpc-testnet.intuition.systems/http"

[etherscan]
intuition = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.intuition.systems/api" }
